"""Seed data for automation tools."""

from __future__ import annotations

SEED_TOOLS = [
    {
        "name": "Testim",
        "slug": "testim",
        "tagline": "AI-accelerated authoring with resilient maintenance",
        "summary": "Testim streamlines authoring with AI suggestions and adaptive locators, ideal for teams prioritising speed and low maintenance overhead.",
        "overall_score": 4.2,
        "pricing_tier": "> $500",
        "ai_capability": 5,
        "ci_cd_support": True,
        "supports_cross_browser": True,
        "has_mobile_support": True,
        "supports_api": True,
        "maintenance_effort": 2,
        "reporting_quality": 4,
        "execution_speed": 4,
        "analytics_depth": 4,
        "community_strength": 3,
        "onboarding_time_minutes": 45,
        "avg_dev_steps": 8,
        "avg_execution_seconds": 28,
        "learning_curve": "low",
        "recommended_team_skill": "low",
        "preferred_project_types": {"web": 5, "mobile": 4, "api": 4, "desktop": 3},
        "languages_supported": ["javascript", "typescript"],
        "criteria_scores": {
            "ai_assistance": 5,
            "reporting_quality": 4,
            "maintenance": 4,
            "execution_speed": 4,
            "cross_browser_support": 4,
            "ci_cd": 5,
            "language_fit": 4,
            "analytics_depth": 4,
            "community_strength": 3,
        },
        "pros": [
            "AI-backed authoring with smart suggestions",
            "Self-healing locators reduce flaky tests",
            "Rich dashboards with stakeholder-ready views",
        ],
        "cons": [
            "Premium pricing tier",
            "Requires onboarding to maximise AI flows",
        ],
        "additional_metadata": {
            "best_for": [
                "Cross-functional teams new to automation",
                "Organisations needing reliable AI maintenance",
            ],
            "execution_notes": "Average execution ~28s using cloud runners",
        },
    },
    {
        "name": "Mabl",
        "slug": "mabl",
        "tagline": "Unified intelligent testing with deep analytics",
        "summary": "Mabl blends low-code authoring with advanced analytics, providing insights for customer journeys and release health.",
        "overall_score": 4.1,
        "pricing_tier": "> $500",
        "ai_capability": 4,
        "ci_cd_support": True,
        "supports_cross_browser": True,
        "has_mobile_support": True,
        "supports_api": True,
        "maintenance_effort": 2,
        "reporting_quality": 5,
        "execution_speed": 4,
        "analytics_depth": 5,
        "community_strength": 3,
        "onboarding_time_minutes": 60,
        "avg_dev_steps": 10,
        "avg_execution_seconds": 24,
        "learning_curve": "medium",
        "recommended_team_skill": "medium",
        "preferred_project_types": {"web": 5, "mobile": 3, "api": 4, "desktop": 2},
        "languages_supported": ["javascript", "typescript", "python"],
        "criteria_scores": {
            "ai_assistance": 4,
            "reporting_quality": 5,
            "maintenance": 4,
            "execution_speed": 4,
            "cross_browser_support": 4,
            "ci_cd": 5,
            "language_fit": 4,
            "analytics_depth": 5,
            "community_strength": 3,
        },
        "pros": [
            "Industry-leading analytics and journey insights",
            "Fast visual change detection",
            "Strong CI/CD hooks and release gates",
        ],
        "cons": [
            "Requires paid tier for full feature set",
            "Authoring model may feel prescriptive for coders",
        ],
        "additional_metadata": {
            "best_for": [
                "Product teams prioritising reporting",
                "QA groups needing customer journey analytics",
            ],
            "execution_notes": "Executes suites in ~23.6s using managed runners",
        },
    },
    {
        "name": "Playwright",
        "slug": "playwright",
        "tagline": "Developer-centric automation for modern apps",
        "summary": "Playwright provides fast, reliable cross-browser automation with broad language support ideal for skilled engineering teams.",
        "overall_score": 3.9,
        "pricing_tier": "free",
        "ai_capability": 2,
        "ci_cd_support": True,
        "supports_cross_browser": True,
        "has_mobile_support": True,
        "supports_api": True,
        "maintenance_effort": 3,
        "reporting_quality": 3,
        "execution_speed": 5,
        "analytics_depth": 3,
        "community_strength": 4,
        "onboarding_time_minutes": 90,
        "avg_dev_steps": 55,
        "avg_execution_seconds": 24,
        "learning_curve": "high",
        "recommended_team_skill": "high",
        "preferred_project_types": {"web": 5, "mobile": 4, "api": 5, "desktop": 3},
        "languages_supported": ["javascript", "typescript", "python", "c#", "java"],
        "criteria_scores": {
            "ai_assistance": 2,
            "reporting_quality": 3,
            "maintenance": 3,
            "execution_speed": 5,
            "cross_browser_support": 5,
            "ci_cd": 5,
            "language_fit": 5,
            "analytics_depth": 3,
            "community_strength": 4,
        },
        "pros": [
            "Fastest execution window (16?30s)",
            "Rich API coverage (web, API, mobile emulation)",
            "First-class CI integrations",
        ],
        "cons": [
            "Steeper learning curve for non-developers",
            "Requires engineers for maintenance",
        ],
        "additional_metadata": {
            "best_for": [
                "High-skill dev teams",
                "Organisations standardising on open source",
            ],
            "execution_notes": "Parallel runs optimise suite performance",
        },
    },
    {
        "name": "Selenium",
        "slug": "selenium",
        "tagline": "Battle-tested framework with maximum flexibility",
        "summary": "Selenium delivers unmatched flexibility and community support, best for teams ready to invest in custom frameworks.",
        "overall_score": 3.4,
        "pricing_tier": "free",
        "ai_capability": 1,
        "ci_cd_support": True,
        "supports_cross_browser": True,
        "has_mobile_support": False,
        "supports_api": False,
        "maintenance_effort": 5,
        "reporting_quality": 2,
        "execution_speed": 3,
        "analytics_depth": 2,
        "community_strength": 5,
        "onboarding_time_minutes": 150,
        "avg_dev_steps": 48,
        "avg_execution_seconds": 33,
        "learning_curve": "high",
        "recommended_team_skill": "high",
        "preferred_project_types": {"web": 5, "mobile": 2, "api": 3, "desktop": 4},
        "languages_supported": ["javascript", "python", "java", "c#"],
        "criteria_scores": {
            "ai_assistance": 1,
            "reporting_quality": 2,
            "maintenance": 1,
            "execution_speed": 3,
            "cross_browser_support": 4,
            "ci_cd": 4,
            "language_fit": 4,
            "analytics_depth": 2,
            "community_strength": 5,
        },
        "pros": [
            "Largest community and ecosystem",
            "Highly customisable for edge cases",
            "Cost-effective with mature tooling",
        ],
        "cons": [
            "High maintenance burden",
            "Basic reporting out of the box",
        ],
        "additional_metadata": {
            "best_for": [
                "Engineering teams needing deep control",
                "Long-lived frameworks with custom stacks",
            ],
            "execution_notes": "Execution speed depends heavily on runner setup",
        },
    },
    {
        "name": "Cypress",
        "slug": "cypress",
        "tagline": "Developer-friendly testing for modern web apps",
        "summary": "Cypress speeds up testing for JavaScript teams with time-travel debugging and intuitive authoring.",
        "overall_score": 3.8,
        "pricing_tier": "< $500",
        "ai_capability": 2,
        "ci_cd_support": True,
        "supports_cross_browser": True,
        "has_mobile_support": False,
        "supports_api": True,
        "maintenance_effort": 3,
        "reporting_quality": 4,
        "execution_speed": 4,
        "analytics_depth": 3,
        "community_strength": 4,
        "onboarding_time_minutes": 60,
        "avg_dev_steps": 18,
        "avg_execution_seconds": 27,
        "learning_curve": "medium",
        "recommended_team_skill": "medium",
        "preferred_project_types": {"web": 5, "mobile": 2, "api": 4, "desktop": 2},
        "languages_supported": ["javascript", "typescript"],
        "criteria_scores": {
            "ai_assistance": 2,
            "reporting_quality": 4,
            "maintenance": 3,
            "execution_speed": 4,
            "cross_browser_support": 4,
            "ci_cd": 4,
            "language_fit": 4,
            "analytics_depth": 3,
            "community_strength": 4,
        },
        "pros": [
            "Time-travel debugging and interactive runner",
            "Strong JavaScript ecosystem integrations",
            "Affordable managed dashboard",
        ],
        "cons": [
            "Limited official mobile coverage",
            "Requires JS/TS comfort level",
        ],
        "additional_metadata": {
            "best_for": [
                "Front-end focused teams",
                "Agile squads iterating quickly",
            ],
            "execution_notes": "Dashboard analytics available in paid tier",
        },
    },
]
